### ISSUE TITLE
Need to add a blog to the site

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/codeforhawaii.github.io#16]
Need to add a blog to the site. Right now, we're debating between:
- Hosted Wordpress
- Self-hosted Ghost
- Hosted Medium

**Comment by rbvea** [comment]
Wait, we're not gonna use Jekyll?

**Comment by ryankanno** [comment]
Ah. Ideally, I want to allow people who aren't developers to be able to write magical goodness about us. I think the Jekyll bar is really low if you're a developer but still really high if you aren't.  Ideally, something that levels the field really flat and the bar really low for everyone. :)

**Comment by ryankanno** [comment]
http://blog.codeforhawaii.org is up. Let's hold off placing it until we have a theme in place and a wee bit of content.

**Comment by ryankanno** [comment]
Closed in 18f2cebf6ee3b0e4f0ddb09a35caf3367ad62335
