### ISSUE TITLE
Vagrant/Jekyll Server

### ISSUE THREAD

**Issue by matthewtrask** [CodeforHawaii/codeforhawaii.github.io#2]
Hey, just a thought, but Jekyll already has a server built it, is it needed to have Vagrant running as well?

if you just run "jekyll serve" itll launch its own web server, and if you do "jekyll serve --watch" itll actively watch for changes in sass/markdown.

**Comment by ryankanno** [comment]
Ah, yes - it's so that if you're a developer that doesn't want to pollute your ruby environment or fight the installation battle -> it'll install everything you need to get up and running without you having to worry about it.

(Vagrant is provided as just another option) :)
