### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by Bytemarks** [CodeforHawaii/codeforhawaii.github.io#20]
Need to add: Municipal Partner: Nicole Velasco, City & County of Honolulu on the About Section list. 

Also need to build out a space to provide the profiles of each of the team leaders.

**Comment by ryankanno** [comment]
This should be separated into two issues.

**Comment by ryankanno** [comment]
Added Nicole - 82e2619a709f7b417a0cfb673ff49dd7c425a091

Created new issue #21 to track a new profile page.
