### ISSUE TITLE
Fix HTML-proofer errors.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/codeforhawaii.github.io#33]
https://travis-ci.org/CodeforHawaii/codeforhawaii.github.io/builds/92349583

**Comment by ryankanno** [comment]
Who broke the build! 0_0 :D

**Comment by ryankanno** [comment]
I fixed these errors in this checkin: 021d4b8f1bd913aa3210f9b710547f9fb36e3eb6

Can you close this if it fixes your issues? (Pretty sure it does).
