### ISSUE TITLE
Down arrow on splash page

### ISSUE THREAD

**Issue by Bytemarks** [CodeforHawaii/codeforhawaii.github.io#5]
Clicking on the down arrow does not move the page down. The only way to navigate is to click the menu at the top.

**Comment by ryankanno** [comment]
That down arrow is linked to the about section. Want to start an issue stating what we should have in that?

**Comment by ryankanno** [comment]
Started at #6

**Comment by ryankanno** [comment]
Closed in 257c1e00e920d42f217af88c40b28108a338b27a
