### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by Bytemarks** [CodeforHawaii/codeforhawaii.github.io#6]
Draft of About Section:

Code for Hawaii is a Code for America Brigade. We are volunteers interested in open data, open knowledge, civic apps, big data, data visualization, APIs and the application of technology to make our communities better. We encourage civic engagement and collaboration with our local government. We are engaged citizens with backgrounds and interest in technology, design, business management, policy and good government.

**Comment by ryankanno** [comment]
Added in 257c1e00e920d42f217af88c40b28108a338b27a
