### ISSUE TITLE
Find actual picture of Hawaii to use as splash image

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/codeforhawaii.github.io#7]
Should find something from here:

https://www.flickr.com/search/?license=1%2C2%2C3%2C4%2C5%2C6%2C9&sort=relevance&text=hawaii%20skyline&advanced=1

See: http://codefordenver.org as an example.

**Comment by Bytemarks** [comment]
I will look around. It would be good to get something unique to Hawaii.

**Comment by Bytemarks** [comment]
Let's go with this photo. Please don't forget to give proper attribution. Thanks! https://www.flickr.com/photos/74274915@N00/994629457/in/photolist-4hfMrZ-9rdnQt-gYQZPu-ipAEd7-pyommb-gafQaZ-93EjYH-qHNH9W-rBprwm-qjRL5x-qyZDEh-gU9ioA-qVnQnk-2vTJFK-9Ehkdf-rDY3v8-a1TA3J-rx8o72-efoV6k-egyfmk-ooUg5P-m4yTTv-ooYgyE-qsR3ds-rtftnH-9nD7kT-2p34Kg-a1UV8U-e4PPkW-nacbFv-5RBzrY-5RBmf9-9nG8RA-j6ERpN-4nKjHF-efhSU4-9zSrY9-pKyNTv-4ywZo5-qG7yS4-ocWw1z-dDcmCJ-qGGaed-qzu8sw-5Rxhbc-qiPQYn-9nD7s8-njKT7x-pGCm1Z-qBA6kk

**Comment by ryankanno** [comment]
Here's the attribution @rbvea : [Port of Honolulu. Sunset.](https://www.flickr.com/photos/74274915@N00/994629457/in/photolist-4hfMrZ-9rdnQt-gYQZPu-ipAEd7-pyommb-gafQaZ-93EjYH-qHNH9W-rBprwm-qjRL5x-qyZDEh-gU9ioA-qVnQnk-2vTJFK-9Ehkdf-rDY3v8-a1TA3J-rx8o72-efoV6k-egyfmk-ooUg5P-m4yTTv-ooYgyE-qsR3ds-rtftnH-9nD7kT-2p34Kg-a1UV8U-e4PPkW-nacbFv-5RBzrY-5RBmf9-9nG8RA-j6ERpN-4nKjHF-efhSU4-9zSrY9-pKyNTv-4ywZo5-qG7yS4-ocWw1z-dDcmCJ-qGGaed-qzu8sw-5Rxhbc-qiPQYn-9nD7s8-njKT7x-pGCm1Z-qBA6kk/) by [Alexander Shchukin](https://www.flickr.com/photos/74274915@N00/), [CC-BY-NC-ND-2.0](https://creativecommons.org/licenses/by-nc-nd/2.0/legalcode)

**Comment by axelson** [comment]
@ryankanno out of curiosity how did you come up with the attribution?

**Comment by ryankanno** [comment]
@axelson Manually. :) There's this plugin [here](http://cogdog.github.io/flickr-cc-helper/), but I don't like they don't link to the license.

**Comment by axelson** [comment]
Ah I see. Too bad they don't build it in to the site.

**Comment by rbvea** [comment]
Closing this, still need to implement #10 though.
