### ISSUE TITLE
Add mission statement to home page

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/codeforhawaii.github.io#9]
We came up with v1 of our mission statement last night - we need to add it to our homepage.

**Comment by ryankanno** [comment]
To foster efficient and fair government through civic engagement by collaborating with government officials and leveraging technologies that promote openness and accountability.

**Comment by matthewtrask** [comment]
Hey dude! Saw this was an issue, checked the repo and didnt see it, so I took care of it for you. Kept it simple and in line with what the about statement was. Hope it works for you guys!
